### ISSUE TITLE
The invisible cluster

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#141]
Maybe not necessary to have an invisible cluster:

![image](https://cloud.githubusercontent.com/assets/4260509/17748126/f405aac0-6485-11e6-9747-6cb856d6c2d7.png)

**Comment by basilgohar** [comment]
@nickjer This issue is about 9 months old, do you still think this is a problem?

**Comment by nickjer** [comment]
I think it still looks odd, would be better with "Please choose a cluster from below..." or something.

**Comment by brianmcmichael** [comment]
I can live with that.
