### ISSUE TITLE
Remove torque specific code from app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#159]
- Completely remove use of osc-machete and osc_machete_rails
- Don't filter out clusters that are torque specific; do filter out clusters that don't have a corresponding ood_job adapter
- Ensure error messages say "An error occurred" instead of "A PBS::Error occurred"
- Auto instantiate proper ood_job adapter for specified cluster

**Comment by brianmcmichael** [comment]
Done at #157
