### ISSUE TITLE
Simplify templates view and management

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#161]
Started here:

https://github.com/OSC/ood-myjobs/pull/160

Reduce the number of main pages to 2. Make the look and feel between the two very similar. Jobs and Templates. We will be getting rid of the separate "My Templates" view. This should simplify the use of the job constructor, and also open the possibility to turn this into a simple Ember or React app.

![screen shot 2017-02-26 at 3 12 37 pm](https://cloud.githubusercontent.com/assets/512333/23343226/113aa972-fc36-11e6-86ee-9eb93c6dc979.png)

![screen shot 2017-02-26 at 3 15 56 pm](https://cloud.githubusercontent.com/assets/512333/23343276/916e59a4-fc36-11e6-9166-8f887cb3f0bc.png)

Templates now have 5 buttons next to the templates list:

1. New Template takes you to the "new template form" that already exists
2. Copy template copies the selected template to My Templates and modifies name (copy 1 etc.) without showing user form, similar to how Jobs copy button works
3. Edit Files opens the file editor to the template directory
4. Open terminal opens the terminal to the template directory
5. Template Default Options opens a form to edit the manifest values (a similar form as the "new template" form. NOTE: for starters we can just open the manifest.yml file in the file editor (?) or show a popover explaining what to do
6. Delete deletes the directory

Of course, these buttons should be disabled if you don't have read/write access to the template, or there are no templates.

**Comment by brianmcmichael** [comment]
> Of course, these buttons should be disabled if you don't have read/write access to the template, or there are no templates.

I'm not sure how I want to display the "open dir" and "open terminal" options for system templates. Here, the user has read, but not write access. I currently disable the options in the development branch, but the user may wish to inspect the system templates. I'm not sure whether to allow this or not. Of course, the system will prevent them from actually editing the system templates, so maybe it would be OK to allow directory access to them.

**Comment by ericfranz** [comment]
Ok so we will just disable the delete button when its a system template.

**Comment by brianmcmichael** [comment]
@ericfranz #160 is in a state of partial requirement of this issue. 

The "Template Options" button has been commented out. This was discussed offline for expediency and the options can be added later.

Once this is merged, the old Templates view and index route should be removed.
