### ISSUE TITLE
Update to Rails 4.2.7.1

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-myjobs#162]
Currently on 4.1.15.

**Comment by ericfranz** [comment]
Lets hold off on this till we confirm we aren't going to temporarily revert to using Rails 4.1.

**Comment by brianmcmichael** [comment]
I don't think this should be closed. This is still an outstanding issue as all of our other apps are on `4.2.7.1`

**Comment by ericfranz** [comment]
I actually closed this because I think whatever code we have on Rails 4.1 that works we should keep it there for now.

**Comment by ericfranz** [comment]
The reason is that the SCL package for Rails 4.1 supports RHEL6&7 and the SCL package for Rails 4.2 is only RHEL7.
