### ISSUE TITLE
Refresh displayed script after editing.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-myjobs#167]
The user leaves the page to edit a script, and then when they return to the page the script does not appear to be modified until they refresh or reselect the job.

I think we can use the `$(document).focus()` event to capture when a user returns to the tab, and then use that event to refresh the displayed script.

**Comment by brianmcmichael** [comment]
This is related to #152 except this solution would not rely on polling.

**Comment by ericfranz** [comment]
I'm okay with trying this out, except this will need to be tested in all our supported browsers. I remember having problems in the past with focus events not working the same.

**Comment by brianmcmichael** [comment]
See https://github.com/OSC/ood-myjobs/pull/168

**Comment by brianmcmichael** [comment]
Closing. Merged.
