### ISSUE TITLE
Using .env.production.local to override .env.production causes bin/setup-production to fail

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#169]
The bin/setup-production script loads the env from the dotenv gem using this command https://github.com/OSC/ood-myjobs/blob/36608f90957504d7f19f08ff332de7d8f433554f/bin/setup-production#L23-L24

When we override using the new method provided by the dotenv gem, the override is not being included.

A temporary workaround is when deploying an app that requires an override of .env.production, just copy that file over .env.production.

This is only for apps that require a database and thus only affects MyJobs for AweSim.

**Comment by ericfranz** [comment]
The simple fix to this should be:

```diff
  # get env vars for DATABASE and DATAROOT
- envs = Dotenv.load(".env.production")
+ envs = Dotenv.load(".env.production.local", ".env.local", ".env.production", ".env")
```

Thats the order that dotenv gem loads the env: https://github.com/bkeepers/dotenv/blob/c1e298042cfdade9cc9930659aefc85a7ee5bb22/lib/dotenv/rails.rb#L58-L65


```ruby
    def load
      Dotenv.load(*dotenv_files)
    end

...

    private

    def dotenv_files
      [
        root.join(".env.#{Rails.env}.local"),
        (root.join(".env.local") unless Rails.env.test?),
        root.join(".env.#{Rails.env}"),
        root.join(".env")
      ].compact
    end
```

**Comment by nickjer** [comment]
This can be handled with a `bin/setup` similar to what I do in the dashboard.
