### ISSUE TITLE
Bug in HTML

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#170]
Missing `<div class="row">` before the `<div class="col-md-7">`:

![image](https://cloud.githubusercontent.com/assets/4260509/24023192/01c54368-0a81-11e7-8059-2f51412b4538.png)

This causes the New Job buttons to be offset a bit...

![image](https://cloud.githubusercontent.com/assets/4260509/24023215/21b80d22-0a81-11e7-95a1-16432a16fc8d.png)

**Comment by brianmcmichael** [comment]
I think this is an aesthetic preference rather than a bug. Currently the "New Job" buttons are in line with the buttons in the panel below it, which was the original design.

Adding the "row" class would shift these to the right, like below. I personally prefer the existing view.

![btns](https://cloud.githubusercontent.com/assets/2374718/24047039/ef8590fc-0afa-11e7-9f0f-9adc14d4ac0c.png)

**Comment by nickjer** [comment]
I am not sure you should be specifying grid columns outside of a row element. I believe, but I could be wrong, you need to specify `<div class="row">`. You can then do some css-foo to align buttons up after that.

Opinion @ericfranz?

**Comment by brianmcmichael** [comment]
It's using the `.container` element as it's parent right now, which is fine.

**Comment by nickjer** [comment]
Rows go in containers, and columns go in rows:

![image](https://cloud.githubusercontent.com/assets/4260509/24053859/b4428df4-0b10-11e7-890e-ebaad53d8daf.png)

Also, although your first button lines up with the first button below it. The same can't be said for the last button in the row.

![image](https://cloud.githubusercontent.com/assets/4260509/24053944/fa92d9a8-0b10-11e7-8d9e-7ee8eade46fa.png)

If you want to have them match up, you would wrap them in `<div class="row">` and then inside of the nested `<div class="panel">` you would wrap the buttons in `<div class="panel-body">`. You would get this:

![image](https://cloud.githubusercontent.com/assets/4260509/24054142/8e67b194-0b11-11e7-909b-e6b0e9eb6fff.png)

**Comment by brianmcmichael** [comment]
It would work here, but I guess I'm not reading those instructions as imperative.
