### ISSUE TITLE
ood_job Status object changed

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#172]
The `OodJob::Status` object now has the `:completed` state. We now use `:undetermined` for existing job states that aren't mapped for a given resource manager adapter.

In particular you may need to [update the code](https://github.com/OSC/ood-myjobs/blob/04eca4613d7493333c7ec90ca2d5ecec1996fc7d/app/models/resource_mgr_adapter.rb#L65-L77) to something along the lines of:

```ruby
  def status_for_ood_job_status(status)
    if status.completed?
      OSC::Machete::Status.passed
    elsif status.queued?
      OSC::Machete::Status.queued
    elsif status.queued_held?
      OSC::Machete::Status.held
    elsif status.suspended?
      OSC::Machete::Status.suspended
    elsif status.running?
      OSC::Machete::Status.running
    else
      OSC::Machete::Status.undetermined
    end
  end
```

**Comment by ericfranz** [comment]
After of course `bundle update ood_job`
