### ISSUE TITLE
Template details pane disappears after refocus event

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#179]
Related to #177 

1. Go to Templates
2. Select a Template. Notice the Template Details pane.
3. Switch browser windows.
4. Switch back (so the window on focus event occurs).
5. Template Details pane disappears.

**Comment by brianmcmichael** [comment]
I'm not experiencing this. Do a hard refresh of your assets and try again.

**Comment by ericfranz** [comment]
Build was wrong. This is not an issue.
