### ISSUE TITLE
OOD install lets users create jobs with no resource manager

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#183]
A fresh OOD install that has a cluster config defined from here:

https://osc.github.io/ood-documentation/installation/add-cluster-config.html

In particular the first one with no resource manager. This causes My Jobs to allow the user to create jobs with no helpful feedback of what is going on. The user will not know what to do from here.

All capabilities of My Jobs should probably be disabled if a resource manager doesn't exist, as well as including a helpful alert message explaining this.

**Comment by brianmcmichael** [comment]
Changes for this modification were inadvertently committed to master at https://github.com/OSC/ood-myjobs/compare/1ce98be6d803...39661f115b5b

Incisions were relatively minor.

Here's where we're at right now:

![myjobs](https://cloud.githubusercontent.com/assets/2374718/25502179/9ec63fc0-2b63-11e7-9543-380c5a15cbe5.png)

I'm open to suggestions on wording.

**Comment by nickjer** [comment]
The wording seems fine to me.

**Comment by nickjer** [comment]
Since this is already committed to master, I am going to close it.
