### ISSUE TITLE
Default template will fail with slurm

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#184]
Clicking this:

![image](https://cloud.githubusercontent.com/assets/4260509/24805520/1589d5de-1b80-11e7-8dea-7f0da4569bb2.png)

gives me a job script that will fail with Slurm:

![image](https://cloud.githubusercontent.com/assets/4260509/24805541/25c25c5a-1b80-11e7-9b58-cda0f75dca71.png)

as it has all those `#PBS` headers...

**Comment by brianmcmichael** [comment]
Proposed fix committed at https://github.com/OSC/ood-myjobs/commit/9cf702bff876af41024cc2a76fbd7977007c4522

Currently untested on a slurm system.

Could benefit from some refactoring, addition of `lsf` script, and and additional script that is used by default when no adapters match.

**Comment by ericfranz** [comment]
Default template now is just hello world https://github.com/OSC/ood-myjobs/blob/631fe04ec7d5ec67b94b85a71dc9e5e37feb4f45/example_templates/default/main_job.sh. However, it needs a shebang at the top.

**Comment by nickjer** [comment]
Just my opinion but I feel this new default script is hard to work with. I had trouble understanding what to remove when generating a script that worked at Utah.

```bash
#!/bin/bash
#SBATCH -p ember-guest
#SBATCH -A owner-guest
#SBATCH -N 1
#SBATCH -t 1:00:00

cd $SLURM_SUBMIT_DIR
echo "Hello World" > output_file

echo "Created output file with 'Hello World'"
```

Maybe, just like the extended info in ActiveJobs, that MyJobs fills in the header info for the corresponding cluster adapter? Or we just leave it blank with comments:

```bash
#!/bin/bash
#PUT JOB HEADERS HERE

echo "Hello World" > output_file

echo "Created output file with 'Hello World'"
```

**Comment by ericfranz** [comment]
We changed the template to just `echo "Hello World"`. After your real world experience here, it probably makes sense to remove the example headers from that script and just have it be:

```sh
#!/bin/bash
# PUT JOB HEADERS HERE

echo "Hello World"
```

But not `#PUT`. Just in case there isn't a resource manager named PUT in the future :-P.

**Comment by nickjer** [comment]
Yeah I agree with the above.

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-myjobs/pull/196
