### ISSUE TITLE
Crash when I click "Job Options"

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#185]
`ood_core` branch --

I clicked "Job Options" for a job and got this:

![image](https://cloud.githubusercontent.com/assets/4260509/24805746/d712521c-1b80-11e7-9ccc-4c10afed0373.png)

**Comment by brianmcmichael** [comment]
Fix committed at https://github.com/OSC/ood-myjobs/commit/e56150fbda36126df0b1c4bfa0dd8a660aba5a01
