### ISSUE TITLE
Remove copyright from footer

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#187]
This appears in the footer of the My Jobs app:

![image](https://cloud.githubusercontent.com/assets/4260509/24829728/52c770f8-1c45-11e7-9a8c-c9ba78e10b51.png)

So this will appear at every Open OnDemand installation. Is this ok or do we need to change?

@basilgohar and/or @ericfranz?

**Comment by ericfranz** [comment]
Lets go ahead and remove this.

**Comment by brianmcmichael** [comment]
This appears in all of our apps, including vncsim and activejobs. Should issues be added to the other repos as well?

**Comment by nickjer** [comment]
VNCSim isn't an OOD app, but we should open up the issue for ActiveJobs.
