### ISSUE TITLE
Not rescuing from exceptions raised in job submit

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#191]
This is for the https://github.com/OSC/ood-myjobs/pull/188 pull request.

When I submit a job that raises `OodCore::JobAdapterError`, I get this instead of the alert message that typically appears:

![image](https://cloud.githubusercontent.com/assets/4260509/25020272/a47474cc-205b-11e7-95fb-d38910cfa82b.png)

**Comment by brianmcmichael** [comment]
Fixed in https://github.com/OSC/ood-myjobs/commit/d7b6a7e35026d1cdb8a9b396d346fd187c3baca6

Please test.

**Comment by nickjer** [comment]
I don't think that is the right exception class. Shouldn't it be:

```
rescue OodCore::JobAdapterError => e
```

**Comment by brianmcmichael** [comment]
Good question. I'm not sure what OodCore throws.

All of the other methods are rescuing `rescue OodCore::Job::Adapter::Exception => e` so if the exception changed from the way it was in `OodJob` we'll need to update all of those blocks.

**Comment by nickjer** [comment]
They should be raising this error:

https://github.com/OSC/ood_core/blob/6b374167a28fc145c89095be81667fc5c1bbda26/lib/ood_core/errors.rb#L14-L15

**Comment by brianmcmichael** [comment]
Fixed at https://github.com/OSC/ood-myjobs/commit/202fba94fc0bd5c75a5023d52a0ea9a21cc86aa8
