### ISSUE TITLE
The templates/ directory has odd behavior

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#193]
The `templates/` directory looks like a git submodule, but isn't. Also there is no `.keep` in there but it expects that directory to exist.

**Comment by ericfranz** [comment]
Introduced in 9cf702bff876af41024cc2a76fbd7977007c4522

**Comment by ericfranz** [comment]
There is not supposed to be a .keep. Its just a directory that may or may not exist, and is not versioned.

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-myjobs/pull/194
