### ISSUE TITLE
Edit job options inline

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#198]
Being able to edit job options inline would be nice. Especially since we offer a disabled selection box for cluster choice, which tricks me from time to time.

**Comment by brianmcmichael** [comment]
We talked about removing the dropdown from that disabled selectpicker to stop tricking you. I don't think it made it into an issue though so it didn't get done.

**Comment by nickjer** [comment]
This was fixed by replacing the disabled selection box with text.
