### ISSUE TITLE
SQLite db files become corrupt if at quota limit

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#231]
Happened I believe twice (not for MyJobs) where a user reached their disk quota size limit and the web app began crashing. After deleting files to free up space, the web app would still continue to crash due to the db file having become corrupt.

I don't remember all the steps I took to fix it, but I believe I had to dump the contents of the db out and begin pruning bad data by hand to rescue most of its contents.

**Comment by nickjer** [comment]
I'd consider this closed if we implement https://github.com/OSC/ood-dashboard/issues/306 as the user will have proper warning when he/she nears quota limit.

**Comment by MorganRodgers** [comment]
Dashboard quota warnings were added in [ood-dashboard 1.30.2](https://github.com/OSC/ood-dashboard/blob/master/CHANGELOG.md#1302---2019-01-02). Closing.
