### ISSUE TITLE
Strip user-supplied account string parameter

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-myjobs#233]
There can be issues with the accounting database when a user begins the account string with a Space char.

Ensure that a string strip is performed on user input for account string, and probably the rest of the user params.

**Comment by ericfranz** [comment]
If we are going to do the strip everywhere, does it make more sense to do this once in ood_core adapter instead

**Comment by nickjer** [comment]
This is also addressed here: https://github.com/OSC/ood_core/issues/53

**Comment by brianmcmichael** [comment]
It makes sense to do it there, but I think it's also up to an app developer to make sure to clean up or normalize user input before transferring it to dependencies.

**Comment by ericfranz** [comment]
Since we have an issue in ood_core to address this, lets not "also" strip the whitespace in My Jobs. Closing issue.

**Comment by nickjer** [comment]
@basilgohar mentioned that the apps should also be responsible for stripping whitespace accepted from the from forms.
