### ISSUE TITLE
Allow sys admin to modify job submission parameters for input fields when editing job

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#242]
The problem observed by University of Arizona:

- this is in regards to PBS Pro
- our library includes a resource-manager agnostic attribute for "account" (for PBS Pro it is added as the command line argument "-A <account_string>")

The issue is that University of Arizona doesn't use this field for accounting purposes. Instead they use the "--group_list <g_list>" for accounting purposes.

We either allow customization at the app level, library level, or make input fields toggle-able. Other suggestions are appreciated.

**Comment by ericfranz** [comment]
With https://github.com/OSC/ood-myjobs/pull/244, Arizona could add a view that overrides `_edit_form_job_attrs.html.erb` by doing:

```sh
sudo mkdir -p /etc/ood/config/apps/myjobs/app/views/workflows
sudo touch /etc/ood/config/apps/myjobs/app/views/workflows/_edit_form_job_attrs.html.erb
```

That would remove the account from the list of options. If we recommend this, however, we should add an automated test that confirms the existence of the `_edit_form_job_attrs.html.erb` partial and complains loudly if this partial does not exist, explaining its purpose for being overridden.

If this works "well" we could consider creating a few other partials for the purpose of customization. Such as the logo and text on the front page.

**Comment by ericfranz** [comment]
Duplicate.
