### ISSUE TITLE
Upgrade to Rails 4.2

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#250]
Follow the directions in http://guides.rubyonrails.org/v4.2/upgrading_ruby_on_rails.html which is more involved than just changing the gem version.

**Comment by brianmcmichael** [comment]
#162

**Comment by brianmcmichael** [comment]
Update to 4.2.10 because of incompatibility with Ruby 2.4
https://github.com/OSC/ood-dashboard/pull/201#issuecomment-345257917
