### ISSUE TITLE
Job Composer can't handle job arrays

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-myjobs#251]
User is attempting to submit a job that specifies a job array, i.e. `#PBS -t 1-12`

Currently, the app crashes and displays the "something went wrong" message, however, the job is still accepted by the system and runs.

Example Error:
```
App 27361 stdout: [2017-11-13 12:11:35 -0500 ] FATAL "NoMethodError (undefined method `[]' for 
nil:NilClass):\n app/models/resource_mgr_adapter.rb:35:in `qstat'\n app/models/workflow.rb:194:in 
`submit'\n app/controllers/workflows_controller.rb:180:in `block in submit'\n 
app/controllers/workflows_controller.rb:175:in `submit'"
```

The immediate issue is that the job can not status an id for a job array, but similar difficulties will arise when attempting to stop or delete one of these jobs. A more detailed proposal will need to be developed to be able to allow job array functionality across all supported job adapters.

**Comment by MorganRodgers** [comment]
Fixed in [2.11.0](https://github.com/OSC/ood-myjobs/blob/master/CHANGELOG.md#2110---2019-01-29).
